### ISSUE TITLE
User Auth Checklist

### ISSUE THREAD

**Issue by Boosqua** [Boosqua/Disorder#2]
# User Auth
## Functionality
- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [ ] Adequate and appropriate seeds

**Comment by ghost** [comment]
change the link colors to purple like the site has them
make the demo login user button look like the login button
errors are not showing up

**Comment by ghost** [comment]
![Screen Shot 2020-10-15 at 10 35 54 AM](https://user-images.githubusercontent.com/30717440/96166066-53fde000-0ed2-11eb-8997-efc89668f280.png)

**Comment by ghost** [comment]
some weird stuff happening with your errors.  also it looks like you still have the redux logger in your console
